(setq org-agenda-files '("~/Org/Personal.org" "~/Org/Work.org"))
(setq agenda-html-file "~/agenda.html")
(setq agenda-text-file nil)
(setq agenda-ics-file "~/agenda.ics")
(setq agenda-arrows t)
(setq agenda-arrow-left "== ")
(setq agenda-arrow-right " =============================")
